export default{
  alarm         : require('@/assets/audio/nintendo/chrono trigger/alarm.mp3'),
  alert         : require('@/assets/audio/nintendo/chrono trigger/alert.mp3'),
  attack        : require('@/assets/audio/nintendo/chrono trigger/attack.mp3'),
  attack_alt    : require('@/assets/audio/nintendo/chrono trigger/attack_alt.mp3'),
  aura_glow     : require('@/assets/audio/nintendo/chrono trigger/aura_glow.mp3'),
  bats          : require('@/assets/audio/nintendo/chrono trigger/bats.mp3'),
  battleStart   : require('@/assets/audio/nintendo/chrono trigger/battleStart.mp3'),
  battleTurn    : require('@/assets/audio/nintendo/chrono trigger/battleTurn.mp3'),
  bekklerLose   : require('@/assets/audio/nintendo/chrono trigger/bekklerLose.mp3'),
  bigWin        : require('@/assets/audio/nintendo/chrono trigger/bigWin.mp3'),
  burning       : require('@/assets/audio/nintendo/chrono trigger/burning.mp3'),
  burst         : require('@/assets/audio/nintendo/chrono trigger/burst.mp3'),
  chant         : require('@/assets/audio/nintendo/chrono trigger/chant.mp3'),
  charm1        : require('@/assets/audio/nintendo/chrono trigger/charm1.mp3'),
  charm2        : require('@/assets/audio/nintendo/chrono trigger/charm2.mp3'),
  confuseTech   : require('@/assets/audio/nintendo/chrono trigger/confuseTech.mp3'),
  continum      : require('@/assets/audio/nintendo/chrono trigger/continum.mp3'),
  croak         : require('@/assets/audio/nintendo/chrono trigger/croak.mp3'),
  crushingSlash : require('@/assets/audio/nintendo/chrono trigger/crushingSlash.mp3'),
  cureMagic     : require('@/assets/audio/nintendo/chrono trigger/cureMagic.mp3'),
  cursor        : require('@/assets/audio/nintendo/chrono trigger/cursor.mp3'),
  curshoriz: require('@/assets/audio/nintendo/chrono trigger/cursor.mp3'),
  cursverti: require('@/assets/audio/nintendo/chrono trigger/cursor.mp3'),
  equip : require('@/assets/audio/nintendo/chrono trigger/cursor.mp3'),
  deltaForce    : require('@/assets/audio/nintendo/chrono trigger/deltaForce.mp3'),
  deltaStorm    : require('@/assets/audio/nintendo/chrono trigger/deltaStorm.mp3'),
  draw          : require('@/assets/audio/nintendo/chrono trigger/draw.mp3'),
  drip          : require('@/assets/audio/nintendo/chrono trigger/drip.mp3'),
  electricArc   : require('@/assets/audio/nintendo/chrono trigger/electricArc.mp3'),
  enemyDie      : require('@/assets/audio/nintendo/chrono trigger/enemyDie.mp3'),
  epochLaunch   : require('@/assets/audio/nintendo/chrono trigger/epochLaunch.mp3'),
  eb_fanfare: require("@/assets/audio/nintendo/earthbound/eb_fanfare.wav"),
  exhaust       : require('@/assets/audio/nintendo/chrono trigger/exhaust.mp3'),
  explosion     : require('@/assets/audio/nintendo/chrono trigger/explosion.mp3'),
  fall          : require('@/assets/audio/nintendo/chrono trigger/fall.mp3'),
  fireMagic     : require('@/assets/audio/nintendo/chrono trigger/fireMagic.mp3'),
  flap_once     : require('@/assets/audio/nintendo/chrono trigger/flap_once.mp3'),
  flapping      : require('@/assets/audio/nintendo/chrono trigger/flapping.mp3'),
  flapping_loop : require('@/assets/audio/nintendo/chrono trigger/flapping_loop.mp3'),
  gainHp        : require('@/assets/audio/nintendo/chrono trigger/gainHp.mp3'),
  gainMp        : require('@/assets/audio/nintendo/chrono trigger/gainMp.mp3'),
  gateActivate  : require('@/assets/audio/nintendo/chrono trigger/gateActivate.mp3'),
  getItem       : require('@/assets/audio/nintendo/chrono trigger/getItem.mp3'),
  itemget1 : require('@/assets/audio/nintendo/chrono trigger/getItem.mp3'),
  itemget2 : require('@/assets/audio/nintendo/chrono trigger/getItem.mp3'),
  grunt         : require('@/assets/audio/nintendo/chrono trigger/grunt.mp3'),
  gulls         : require('@/assets/audio/nintendo/chrono trigger/gulls.mp3'),
  heckran       : require('@/assets/audio/nintendo/chrono trigger/heckran.mp3'),
  iceMagic      : require('@/assets/audio/nintendo/chrono trigger/iceMagic.mp3'),
  jumpTech      : require('@/assets/audio/nintendo/chrono trigger/jumpTech.mp3'),
  lavos         : require('@/assets/audio/nintendo/chrono trigger/lavos.mp3'),
  lavosHeart    : require('@/assets/audio/nintendo/chrono trigger/lavosHeart.mp3'),
  // lavos  music clip    : require('@/assets/audio/nintendo/chrono trigger/lavos music clip.mp3'),
  lavosRain     : require('@/assets/audio/nintendo/chrono trigger/lavosRain.mp3'),
  leeneBell     : require('@/assets/audio/nintendo/chrono trigger/leeneBell.mp3'),
  lightning     : require('@/assets/audio/nintendo/chrono trigger/lightning.mp3'),
  lightningMagic: require('@/assets/audio/nintendo/chrono trigger/lightningMagic.mp3'),
  loseMusic     : require('@/assets/audio/nintendo/chrono trigger/loseMusic.mp3'),
  magicBlast    : require('@/assets/audio/nintendo/chrono trigger/magicBlast.mp3'),
  megaBomb      : require('@/assets/audio/nintendo/chrono trigger/megaBomb.mp3'),
  miss          : require('@/assets/audio/nintendo/chrono trigger/miss.mp3'),
  buy1 : require('@/assets/audio/nintendo/chrono trigger/miss.mp3'),
  buy2: require('@/assets/audio/nintendo/chrono trigger/miss.mp3'),
  monsterRoar1  : require('@/assets/audio/nintendo/chrono trigger/monsterRoar1.mp3'),
  monsterRoar2  : require('@/assets/audio/nintendo/chrono trigger/monsterRoar2.mp3'),
  onscreen      : require('@/assets/audio/nintendo/chrono trigger/onscreen.mp3'),
  organ         : require('@/assets/audio/nintendo/chrono trigger/organ.mp3'),
  ozzie         : require('@/assets/audio/nintendo/chrono trigger/ozzie.mp3'),
  pat           : require('@/assets/audio/nintendo/chrono trigger/pat.mp3'),
  pat_3x        : require('@/assets/audio/nintendo/chrono trigger/pat_3x.mp3'),
  psilearn: '',
// pat_3x (padded)      : require('@/assets/audio/nintendo/chrono trigger/pat_3x (padded).mp3'),
  portal        : require('@/assets/audio/nintendo/chrono trigger/portal.mp3'),
// portal reverb        : require('@/assets/audio/nintendo/chrono trigger/portal reverb.mp3'),
  roboReady     : require('@/assets/audio/nintendo/chrono trigger/roboReady.mp3'),
  robo_talk     : require('@/assets/audio/nintendo/chrono trigger/robo_talk.mp3'),
  roboTech      : require('@/assets/audio/nintendo/chrono trigger/roboTech.mp3'),
  rumble        : require('@/assets/audio/nintendo/chrono trigger/rumble.mp3'),
  rustle        : require('@/assets/audio/nintendo/chrono trigger/rustle.mp3'),
// sad    music clip    : require('@/assets/audio/nintendo/chrono trigger/sad music clip.mp3'),
  savePoint     : require('@/assets/audio/nintendo/chrono trigger/savePoint.mp3'),
  sealedBoxMusic: require('@/assets/audio/nintendo/chrono trigger/sealedBoxMusic.mp3'),
  shadowMagic   : require('@/assets/audio/nintendo/chrono trigger/shadowMagic.mp3'),
  shot          : require('@/assets/audio/nintendo/chrono trigger/shot.mp3'),
  slash1        : require('@/assets/audio/nintendo/chrono trigger/slash1.mp3'),
  slash2        : require('@/assets/audio/nintendo/chrono trigger/slash2.mp3'),
  slash3        : require('@/assets/audio/nintendo/chrono trigger/slash3.mp3'),
  sleepMusic    : require('@/assets/audio/nintendo/chrono trigger/sleepMusic.mp3'),
  spinout       : require('@/assets/audio/nintendo/chrono trigger/spinout.mp3'),
  squeak        : require('@/assets/audio/nintendo/chrono trigger/squeak.mp3'),
  step          : require('@/assets/audio/nintendo/chrono trigger/step.mp3'),
  swish         : require('@/assets/audio/nintendo/chrono trigger/swish.mp3'),
  thump1        : require('@/assets/audio/nintendo/chrono trigger/thump1.mp3'),
  thump2        : require('@/assets/audio/nintendo/chrono trigger/thump2.mp3'),
  type          : require('@/assets/audio/nintendo/chrono trigger/type.mp3'),
  tyrano        : require('@/assets/audio/nintendo/chrono trigger/tyrano.mp3'),
  useHealingItem: require('@/assets/audio/nintendo/chrono trigger/useHealingItem.mp3'),
  waterMagic    : require('@/assets/audio/nintendo/chrono trigger/waterMagic.mp3'),
}
