// import NintendoNews from "@/assets/audio/nintendo/switch/News.wav"
export default {
  Album     : require('@/assets/audio/nintendo/switch/Album.wav'),
  Bing      : require('@/assets/audio/nintendo/switch/Bing.wav'),
  Border    : require('@/assets/audio/nintendo/switch/Border.wav'),
  Controller: require('@/assets/audio/nintendo/switch/Controller.wav'),
  Dada0     : require('@/assets/audio/nintendo/switch/Dada 0.wav'),
  Dada1     : require('@/assets/audio/nintendo/switch/Dada 1.wav'),
  Dada2     : require('@/assets/audio/nintendo/switch/Dada 2.wav'),
  Dada3     : require('@/assets/audio/nintendo/switch/Dada 3.wav'),
  Dodo      : require('@/assets/audio/nintendo/switch/Dodo.wav'),
  EnterBack : require('@/assets/audio/nintendo/switch/Enter & Back.wav'),
  Error     : require('@/assets/audio/nintendo/switch/Error.wav'),
  Eshop     : require('@/assets/audio/nintendo/switch/Eshop.wav'),
  EshopIntro: require('@/assets/audio/nintendo/switch/Eshop Intro.wav'),
  Home      : require('@/assets/audio/nintendo/switch/Home.wav'),
  Icons     : require('@/assets/audio/nintendo/switch/Icons.wav'),
  Jig0      : require('@/assets/audio/nintendo/switch/Jig 0.wav'),
  Jig1      : require('@/assets/audio/nintendo/switch/Jig 1.wav'),
  Klick     : require('@/assets/audio/nintendo/switch/Klick.wav'),
  Loading   : require('@/assets/audio/nintendo/switch/Loading.wav'),
  News      : require('@/assets/audio/nintendo/switch/News.wav'),
  Nock      : require('@/assets/audio/nintendo/switch/Nock.wav'),
  Popup     : require('@/assets/audio/nintendo/switch/Popup + Run Title.wav'),
  Select    : require('@/assets/audio/nintendo/switch/Select.wav'),
  Settings  : require('@/assets/audio/nintendo/switch/Settings.wav'),
  Standby   : require('@/assets/audio/nintendo/switch/Standby.wav'),
  ThisOne   : require('@/assets/audio/nintendo/switch/This One.wav'),
  Tick      : require('@/assets/audio/nintendo/switch/Tick.wav'),
  TrunOn    : require('@/assets/audio/nintendo/switch/Turn On.wav'),
  TurnOff   : require('@/assets/audio/nintendo/switch/Turn Off.wav'),
  User      : require('@/assets/audio/nintendo/switch/User.wav'),
  GameBoy   : require('@/assets/audio/nintendo/nintendo-game-boy-startup.mp3'),
}