export const FOOD_OPTIONS = [
  { value: "Apple", icon: "fa-apple-alt" },
  { value: "Bacon", icon: "fa-bacon" },
  // { value: "Banana", icon: "fa-banana" },
  // { value: "Beer", icon: "fa-beer" },
  { value: "Bread", icon: "fa-bread-slice" },
  { value: "Burger", icon: "fa-hamburger" },
  { value: "Burrito", icon: "fa-burrito" },
  { value: "Cake", icon: "fa-birthday-cake" },
  { value: "Candy Cane", icon: "fa-candy-cane" },
  { value: "Candy Corn", icon: "fa-candy-corn" },
  { value: "Carrot", icon: "fa-carrot" },
  { value: "Cheese", icon: "fa-cheese" },
  { value: "Cheeseburger", icon: "fa-cheeseburger" },
  // { value: "Cocktail", icon: "fa-cocktail" },
  { value: "Coffee", icon: "fa-coffee" },
  { value: "Cookie", icon: "fa-cookie" },
  // { value: "Cookie Bite", icon: "fa-cookie-bite" },
  { value: "Corn", icon: "fa-corn" },
  { value: "Croissant", icon: "fa-croissant" },
  { value: "Drumstick", icon: "fa-drumstick-bite" },
  { value: "Egg", icon: "fa-egg" },
  { value: "Fish", icon: "fa-fish" },
  { value: "French Fries", icon: "fa-french-fries" },
  { value: "Fried Egg", icon: "fa-egg-fried" },
  { value: "Hotdog", icon: "fa-hotdog" },
  { value: "Ice Cream", icon: "fa-ice-cream" },
  { value: "Lemon", icon: "fa-lemon" },
  { value: "Pepper", icon: "fa-pepper-hot" },
  { value: "Pie", icon: "fa-pie" },
  { value: "Pizza", icon: "fa-pizza-slice" },
  { value: "Popcorn", icon: "fa-popcorn" },
  { value: "Salad", icon: "fa-salad" },
  { value: "Sandwich", icon: "fa-sandwich" },
  { value: "Sausage", icon: "fa-sausage" },
  { value: "Smoothie", icon: "fa-smoothie" },
  // { value: "Soda", icon: "fa-glass-cheers" },
  { value: "Steak", icon: "fa-meat" },
  { value: "Taco", icon: "fa-taco" },
  // { value: "Wine", icon: "fa-wine-glass" }
];

export default FOOD_OPTIONS;