<template>
  <ion-header>
    <ion-toolbar class="rpg-box">
      <ion-buttons slot="start">
        <ion-button
          color="medium"
          @click="closeModal"
          class="font-medium"
        >
          <i class="fas fa-times text-xl mr-2"/>
        </ion-button>
      </ion-buttons>
      <ion-title class="text-xl font-bold">New Profile</ion-title>
      <ion-buttons slot="end">
        <ion-button
          :disabled="!favoriteFood || !favoriteThing || !jobClass || !fullName"
          @click="clickSaveProfile"
          class="font-medium"
          color="rpg"
        >
          Save
          <i class="fad fa-save text-xl ml-2"></i>
        </ion-button>
      </ion-buttons>
      <ion-item
        lines="none"
        slot="secondary"
        v-if="$props.showIsAdult"
      >
        <ion-label class="font-medium"> Adult </ion-label>
        <ion-checkbox
          readonly
          v-model="isAdult"
          slot="end"
        > </ion-checkbox>
      </ion-item>
    </ion-toolbar>
  </ion-header>
  <ion-content class="bg-slide rpg-box ion-padding">
    <!-- Success splash modal -->
    <div 
      class="success-splash-overlay" 
      v-if="showSuccessSplash"
      @click="showSuccessSplash = false"
    >
      <div class="success-splash-content">
        <div class="success-icon">
          <i class="fad fa-check-circle text-success fa-5x"></i>
        </div>
        <h2 class="text-2xl font-bold mt-4">Profile Created!</h2>
        <p class="text-lg mt-2">Your adventure awaits!</p>
        <div class="confetti-container">
          <!-- Confetti elements generated by CSS -->
          <div v-for="n in 20" :key="n" class="confetti-piece" :style="`--delay: ${n * 0.1}s; --rotation: ${n * 18}deg;`"></div>
        </div>
      </div>
    </div>

    <!-- Audio for fanfare -->
    <audio ref="fanfareAudio" preload="auto">
      <source src="/sounds/success-fanfare.mp3" type="audio/mpeg">
      <!-- Fallback source -->
      <source src="/sounds/success-fanfare.ogg" type="audio/ogg">
    </audio>

    <!-- v-if="activeSegment === 'info'" -->
    <ion-grid class="md:max-w-[60vw] mb-7 mx-auto flex flex-col items-center justify-center">
      <gamer-card
        :profile="newProfile"
        class="w-full"
        v-model:avatarIndex="avatarIndex"
        v-model:jobClass="jobClass"
        v-model:favoriteFood="favoriteFood"
      />

      <ion-card class="w-full shadow-lg">
        <ion-segment
          v-model="activeSegment"
          class="overflow-visible p-2 mx-2"
        >
          <ion-segment-button
            value="info"
            class="segment-button-custom overflow-visible"
            color="rpg"
          >
            <div class="flex flex-col items-center gap-1 overflow-visible">
              <i class="fad fa-user fa-2x"></i>
              <span class="text-xs">Who</span>
            </div>
          </ion-segment-button>
          <ion-segment-button
            value="account"
            class="segment-button-custom overflow-visible"
            color="rpg"
          >
            <div class="flex flex-col items-center gap-1 overflow-visible">
              <i class="fad fa-fingerprint fa-2x"></i>
              <span class="text-xs">Pin</span>
            </div>
          </ion-segment-button>
          <ion-segment-button
            value="features"
            class="segment-button-custom"
            color="rpg"
          >
            <div class="flex flex-col items-center gap-1">
              <i class="fad fa-gamepad fa-2x text-primary"></i>
              <span class="text-xs">On/Off</span>
            </div>
          </ion-segment-button>
          <ion-segment-button
            value="preferences"
            class="segment-button-custom flex-shrink"
            color="rpg"
          >
            <div class="flex flex-col items-center gap-1">
              <i class="fad fa-cogs fa-2x"></i>
              <!-- <span class="text-xs">Preferences</span> -->
            </div>
          </ion-segment-button>
        </ion-segment>
      </ion-card>

      <ion-card
        v-if="activeSegment === 'info'"
        class="w-full"
      >
        <ion-list class="p-0">
          <!-- Avatar Selection Row -->
          <ion-item class="avatar-row py-2">
            <div class="flex items-center w-full gap-4">
              <div
                class="avatar-preview w-20 h-20 rounded-full bg-gray-200 flex items-center justify-center cursor-pointer hover:opacity-80"
                @click="isAvatarSelectorOpen = true"
                id="avatar-trigger"
              >
                <img
                  :src="currentAvatar"
                  alt="Selected avatar"
                  class="w-full h-full object-cover rounded-full"
                />
              </div>
              <div class="flex-1">
                <ion-label class="font-medium mb-2">Choose Avatar
                  <p>Click the avatar to select from all available options</p>
                </ion-label>

              </div>
            </div>
          </ion-item>

          <!-- Form Fields in 2 Columns -->
          <ion-grid>
            <ion-row>
              <!-- Left Column -->
              <ion-col
                size="12"
              >
                <ion-item class="py-1">
                  <div class="w-full">
                    <ion-label class="font-medium block mb-1">
                      <!-- Full Name -->
                      <p class="text-sm text-gray-500">First M. Last aka Nickname</p>
                    </ion-label>
                    <ion-input
                      v-model="fullName"
                      class="bg-gray-50 rounded-lg mt-1"
                      placeholder="Enter your full name"
                    ></ion-input>
                  </div>
                </ion-item>

                <ion-item class="py-1">
                  <div class="w-full">
                    <ion-label class="font-medium block mb-1">
                      <!-- Favorite Thing -->
                      <p>What's your most favorite thing?</p>
                    </ion-label>
                    <ion-input
                      v-model="favoriteThing"
                      class="bg-gray-50 rounded-lg mt-1"
                      placeholder="Enter your favorite thing"
                    ></ion-input>
                  </div>
                </ion-item>
              </ion-col>

              <!-- Right Column -->
              <ion-col
                size="12"
                size-md="6"
              >
                <ion-item class="py-1">
                  <div class="w-full">
                    <ion-label class="font-medium block mb-1">
                      <!-- Job Class -->
                      <p class="text-sm text-gray-500">Pick a starter job class</p>
                    </ion-label>
                    <ion-select
                      v-model="jobClass"
                      placeholder="Select starter class..."
                      class=" w-full"
                      interface="action-sheet"
                      expand="block"
                      :interface-options="{
                        header: 'Choose Your Job Class',
                        subHeader: 'Select your starting role'
                      }"
                    >
                      <ion-select-option
                        v-for="(job, index) in jobClassOptions"
                        :key="index"
                        :value="job.name"
                        class="w-full"
                      >
                        <i :class="`fad ${job.icon} mr-2`"></i>
                        {{ job.name }}
                      </ion-select-option>
                    </ion-select>
                  </div>
                </ion-item>

                <ion-item class="py-1 w-full">
                  <div class="w-full">
                    <ion-label class="font-medium block mb-1">
                      <!-- Favorite Food -->
                      <p class="text-sm text-gray-500">Favorite food from the bunch</p>
                    </ion-label>
                    <ion-select
                      v-model="favoriteFood"
                      placeholder="Select favorite food..."
                      class="mt-1 w-full"
                      interface="action-sheet"
                      expand="full"
                      :interface-options="{
                        header: 'Choose Your Favorite Food',
                        subHeader: 'What do you enjoy eating most?'
                      }"
                    >
                      <ion-select-option
                        v-for="food in foodOptions"
                        :key="food.value"
                        :value="food.value"
                      >
                        <i :class="`fad ${food.icon} mr-2`"></i>
                        {{ food.value }}
                      </ion-select-option>
                    </ion-select>
                  </div>
                </ion-item>
              </ion-col>
            </ion-row>
          </ion-grid>
        </ion-list>
      </ion-card>

      <!-- Avatar Selector -->
      <avatar-selector
        v-model="avatarIndex"
        :is-open="isAvatarSelectorOpen"
        :max-avatar-index="maxAvatarIndex"
        @close="isAvatarSelectorOpen = false"
        @selected="selectAvatar"
        :fullscreen="true"
      />

      <ion-card v-if="activeSegment === 'account'">
        <ion-list class="p-0">
          <ion-item class="p-4">
            <div class="w-full">
              <ion-label class="font-medium block mb-1">
                Email Address
                <p class="text-sm text-gray-500">Used for account recovery and notifications</p>
              </ion-label>
              <ion-input
                v-model="email"
                type="email"
                autocomplete="off"
                class="bg-gray-50 rounded-lg mt-1"
                placeholder="Enter your email address"
              ></ion-input>
            </div>
          </ion-item>

          <ion-item class="p-4">
            <div class="w-full">
              <ion-label class="font-medium block mb-1">
                Passcode Protection
                <p class="text-sm text-gray-500">4-digit PIN to secure your profile</p>
              </ion-label>
              <div class="flex gap-2 mt-2">
                <div
                  v-for="i in 4"
                  :key="i"
                  class="flex-1"
                >
                  <input
                    :ref="'passcode' + i"
                    inputmode="numeric"
                    maxlength="1"
                    class="w-full h-12 text-center text-xl font-bold bg-gray-50 border border-gray-300 rounded-lg focus:border-primary focus:ring-2 focus:ring-primary-light"
                    v-model="passcodeDigits[i - 1]"
                    @input="handlePasscodeInput($event, i)"
                    @keydown="handleKeyDown($event, i)"
                    :type="passcodeType"
                  />
                </div>
              </div>
            </div>
          </ion-item>

          <ion-item class="p-4">
            <div class="flex items-center justify-between w-full">
              <ion-label>
                Show Passcode
                <p>Toggle to reveal or hide your passcode</p>
              </ion-label>
              <ion-toggle
                :checked="!hidePasscode"
                @ionChange="hidePasscode = !$event.detail.checked"
                class="ml-4"
              ></ion-toggle>
            </div>
          </ion-item>

          <ion-item class="p-4">
            <div class="flex items-center justify-between w-full">
              <ion-label>
                Security Questions
                <p class="text-sm text-gray-500">Add security questions to recover your account</p>
              </ion-label>
              <ion-button
                fill="outline"
                size="small"
                class="ml-4"
              >
                <i class="fad fa-shield-check mr-2"></i>
                Setup
              </ion-button>
            </div>
          </ion-item>
        </ion-list>
      </ion-card>

      <ion-card
        v-if="activeSegment === 'features'"
        class="w-full"
      >
        <ion-list class="p-0">
          <ion-item
            button
            @click="toggleReward"
            class="p-4"
          >
            <div class="flex items-center justify-between w-full">
              <ion-label class="font-medium">
                Buy from Shops
                <p class="text-sm text-gray-500">Allowed this player access to shops and purchase rewards.</p>
              </ion-label>
              <ion-checkbox
                v-model="features.rewards"
                @click.stop
                color="rpg"
              />
            </div>
          </ion-item>

          <ion-item
            button
            @click="toggleGoal"
            class="py-2"
          >
            <div class="flex items-center justify-between w-full">
              <ion-label class="font-medium">
                Save towards Goals
                <p class="text-sm text-gray-500">Allowed player access to the banks and saves toward goals.</p>
              </ion-label>
              <ion-checkbox
                v-model="features.goals"
                @click.stop
                class="ml-4"
                color="rpg"
              />
            </div>
          </ion-item>

          <ion-item
            button
            @click="toggleBattles"
            class="p-4"
          >
            <div class="flex items-center justify-between w-full">
              <ion-label class="font-medium">
                Random Battles
                <p class="text-sm text-gray-500">Turn on/off random battles. If off, players will have to manually check
                  their achievements.</p>
              </ion-label>
              <ion-checkbox
                v-model="features.battles"
                @click.stop
                class="ml-4"
                color="rpg"
              />
            </div>
          </ion-item>

          <ion-item
            button
            @click="toggleCommunity"
            class="p-4"
          >
            <div class="flex items-center justify-between w-full">
              <ion-label class="font-medium">
                Participate in Town Hall
                <p class="text-sm text-gray-500">For players who want to participate in Town Hall.</p>
              </ion-label>
              <ion-checkbox
                v-model="features.community"
                @click.stop
                class="ml-4"
                color="rpg"
             />
            </div>
          </ion-item>
        </ion-list>
      </ion-card>
      <InputSettings v-if="activeSegment === 'preferences'" />
    </ion-grid>
  </ion-content>
</template>
<script lang="ts" src="./AddProfile.ts"></script>
<style scoped>
.segment-button-custom {
  --indicator-color: white;
  --color-checked: white;
  --background-hover: white;

  transition: all 0.3s ease;
}


.segment-button-custom:hover i {
  transform: scale(1.1);
}

.avatar-preview {
  box-shadow: 0 4px 6px -1px rgba(0, 0, 0, 0.1), 0 2px 4px -1px rgba(0, 0, 0, 0.06);
  transition: transform 0.3s ease;
}

.avatar-preview:hover {
  transform: scale(1.05);
}

ion-card {
  border-radius: 1rem;
  box-shadow: 0 4px 6px -1px rgba(0, 0, 0, 0.1), 0 2px 4px -1px rgba(0, 0, 0, 0.06);
  transition: transform 0.3s ease, box-shadow 0.3s ease;
}

ion-card:hover {
  transform: translateY(-2px);
  box-shadow: 0 10px 15px -3px rgba(0, 0, 0, 0.1), 0 4px 6px -2px rgba(0, 0, 0, 0.05);
}

ion-item {
  --padding-start: 1rem;
  --inner-padding-end: 1rem;
  --background-hover: var(--ion-color-light-tint);
  transition: background-color 0.2s ease;
}

ion-button {
  --box-shadow: none;
  transition: transform 0.2s ease;
}

ion-button:not([disabled]):hover {
  transform: translateY(-1px);
}

.rpg-box {
  background: rgba(255, 255, 255, 0.95);
  backdrop-filter: blur(10px);
}

/* Add slide transition for segments */
ion-content {
  --background: linear-gradient(135deg, var(--ion-color-light) 0%, var(--ion-color-light-shade) 100%);
}

ion-card {
  animation: slideIn 0.3s ease-out;
}

@keyframes slideIn {
  from {
    opacity: 0;
    transform: translateY(20px);
  }

  to {
    opacity: 1;
    transform: translateY(0);
  }
}

/* Custom toggle styling */
ion-toggle {
  --background: var(--ion-color-medium);
  --background-checked: var(--ion-color-primary);
  --handle-background: var(--ion-color-light);
  --handle-background-checked: var(--ion-color-light);
}

.fullscreen-modal {
  --width: 100%;
  --height: 100%;
  --border-radius: 0;
}

.avatar-grid {
  display: grid;
  grid-template-columns: repeat(auto-fill, minmax(100px, 1fr));
  gap: 1rem;
  padding: 1rem;
}

.avatar-item {
  cursor: pointer;
  border-radius: 50%;
  overflow: hidden;
  aspect-ratio: 1;
  transition: transform 0.2s ease;
  box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1);
}

.avatar-item:hover {
  transform: scale(1.05);
  box-shadow: 0 6px 12px rgba(0, 0, 0, 0.15);
}

.avatar-image {
  width: 100%;
  height: 100%;
  object-fit: cover;
}

/* Success Splash Styles */
.success-splash-overlay {
  position: fixed;
  top: 0;
  left: 0;
  right: 0;
  bottom: 0;
  background-color: rgba(0, 0, 0, 0.7);
  display: flex;
  align-items: center;
  justify-content: center;
  z-index: 9999;
  animation: fadeIn 0.5s ease-out;
}

.success-splash-content {
  background: white;
  padding: 2rem;
  border-radius: 1rem;
  text-align: center;
  box-shadow: 0 10px 25px rgba(0, 0, 0, 0.2);
  position: relative;
  width: 80%;
  max-width: 400px;
  animation: scaleIn 0.5s cubic-bezier(0.175, 0.885, 0.32, 1.275);
}

.success-icon {
  animation: bounceIn 0.8s cubic-bezier(0.68, -0.55, 0.27, 1.55);
}

/* Confetti animations */
.confetti-container {
  position: absolute;
  top: 0;
  left: 0;
  width: 100%;
  height: 100%;
  overflow: hidden;
  pointer-events: none;
}

.confetti-piece {
  position: absolute;
  width: 10px;
  height: 20px;
  background: linear-gradient(138deg, #f0cb35 0%, #c02425 100%);
  top: -10px;
  left: calc(50% - 5px);
  opacity: 0;
  animation: confetti-fall 3s ease-in-out forwards var(--delay);
  transform: rotate(var(--rotation));
}

.confetti-piece:nth-child(2n) {
  background: linear-gradient(138deg, #43cea2 0%, #185a9d 100%);
  width: 12px;
  height: 12px;
  border-radius: 50%;
}

.confetti-piece:nth-child(3n) {
  background: linear-gradient(138deg, #ff512f 0%, #dd2476 100%);
  width: 15px;
  height: 8px;
}

.confetti-piece:nth-child(4n) {
  background: linear-gradient(138deg, #3494e6 0%, #ec6ead 100%);
  width: 8px;
  height: 15px;
}

@keyframes fadeIn {
  from { opacity: 0; }
  to { opacity: 1; }
}

@keyframes scaleIn {
  from { transform: scale(0.8); opacity: 0; }
  to { transform: scale(1); opacity: 1; }
}

@keyframes bounceIn {
  0% { transform: scale(0); opacity: 0; }
  60% { transform: scale(1.2); opacity: 1; }
  100% { transform: scale(1); }
}

@keyframes confetti-fall {
  0% {
    transform: translateY(0) rotate(var(--rotation));
    opacity: 1;
  }
  100% {
    transform: translateY(calc(100vh)) rotate(calc(var(--rotation) + 360deg));
    opacity: 0;
  }
}
</style>
